carts/urls.py
from django.conf.urls import url
from . views import carthome, cartupdate, checkout_home
from django.urls import path, include

app_name='carts'
urlpatterns =[
	path('', carthome, name='carthome'),
	path('checkout_home/', checkout_home, name='checkout'),
    path('cartupdate/', cartupdate, name='cartupdate'),
]

working/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from products.views import ProductListView, ProductDetailView,upvote, addListing
from carts.views import carthome



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home_page'),
    path('products/', ProductListView.as_view(), name='product_page'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='detail_page'),
    path('<int:product_id>/upvote', upvote, name='prod_upvote'),
    path('addListing', addListing, name='addListing_page'),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls', namespace= 'carts')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

working/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from products.models import Product, Category
from django.utils import timezone
from django.views.generic.edit import CreateView
from django import forms
from carts.models import Cart




def homepage(request): 
	products = Product.objects.order_by('-votes_total')
	return render(request, 'home_page.html',{'products':products}) 

working/templates/base.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>


	<meta charset="utf-8"> <!--utf-8 is character encoding capable of encoding all characters on the web. -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!--X-UA-Compatible tag allows me to choose what version of IE the page should be rendered as-->
	<meta name="viewport" content="width=device-width, initial-scale=1"> <!--This means that the browser will (probably) render the width of the page at the width of its own screen.-->
	<title> The Marketplace</title>

	<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css'  %}">
	<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-slider.css' %}">
	<!-- Font Awesome -->
	<link href="{% static '/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Owl Carousel -->
	<link href="{% static '/slick-carousel/slick/slick.css' %}" rel="stylesheet">
	<link href="{% static '/slick-carousel/slick/slick-theme.css' %}" rel="stylesheet">
	<!-- Fancy Box -->
	<link href="{% static '/fancybox/jquery.fancybox.pack.css' %}" rel="stylesheet">
	<link href="{% static '/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
	<!-- CUSTOM CSS -->
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="https://kit.fontawesome.com/192fcbc1c8.js"></script>

</head>
{% url 'carts:carthome' as cart_url %}
{% url 'home_page' as home_url %}
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-expand-lg navbar-light navigation"> <!-- Navbars require a wrapping .navbar with .navbar-expand{-sm|-md|-lg|-xl} for responsive collapsing and color scheme classes. -->
					<a class="navbar-brand" href="{% url 'home_page' %}">
						<img src="{% static '/images/logo.png' %}" height= 30 width= 30 >
					Marketplace
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto main-nav ">
						<li class="nav-item {% if request.path == home_url %} active {% endif %}" >
							<a class="nav-link" href="{% url 'home_page' %}">Home</a>
						</li>
						<li class="nav-item dropdown dropdown-slide">
							<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="">Dashboard<span><i class="fa fa-angle-down"></i></span>
							</a>

							<!-- Dropdown list -->
							<div class="dropdown-menu">
								<a class="dropdown-item" href="dashboard.html">Dashboard</a>
								<a class="dropdown-item" href="dashboard-my-ads.html">Dashboard My Ads</a>
								<a class="dropdown-item" href="dashboard-favourite-ads.html">Dashboard Favourite Ads</a>
								<a class="dropdown-item" href="dashboard-archived-ads.html">Dashboard Archived Ads</a>
								<a class="dropdown-item" href="dashboard-pending-ads.html">Dashboard Pending Ads</a>
							</div>
						</li>
						<li class="nav-item dropdown dropdown-slide">
							<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Pages <span><i class="fa fa-angle-down"></i></span>
							</a>
							<!-- Dropdown list -->
							<div class="dropdown-menu">
								<a class="dropdown-item" href="about-us.html">About Us</a>
								<a class="dropdown-item" href="contact-us.html">Contact Us</a>
								<a class="dropdown-item" href="user-profile.html">User Profile</a>
								<a class="dropdown-item" href="404.html">404 Page</a>
								<a class="dropdown-item" href="package.html">Package</a>
								<a class="dropdown-item" href="single.html">Single Page</a>
								<a class="dropdown-item" href="store.html">Store Single</a>
								<a class="dropdown-item" href="single-blog.html">Single Post</a>
								<a class="dropdown-item" href="blog.html">Blog</a>

							</div>
						</li>
						<li class="nav-item dropdown dropdown-slide">
							<a class="nav-link dropdown-toggle" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Listing <span><i class="fa fa-angle-down"></i></span>
							</a>
							<!-- Dropdown list -->
							<div class="dropdown-menu">
								<a class="dropdown-item" href="category.html">Ad-Gird View</a>
								<a class="dropdown-item" href="ad-listing-list.html">Ad-List View</a>
							</div>
						</li>
						<li class="nav-item {% if request.path == cart_url %} active {% endif %}">
							<a class="nav-link" href="{% url 'carts:carthome' %}">{{ request.session.cart_items }} <i class="fas fa-shopping-cart"></i> </a>
						</li>
					</ul>
					<ul class="navbar-nav ml-auto mt-10">
						<li class="nav-item">
							{% if user.is_authenticated %}
							<a class="nav-link login-button" href= "javascript:{document.getElementById('logout').submit()}" >Logout</a>
							<form id="logout" method="POST" action="{% url 'logout_page' %}">
							{% csrf_token %}
							<input type="hidden"/>

							</form>

							<li class="nav-item">
							<a class="nav-link text-white add-button" href="{% url 'addListing_page' %}"><i class="fa fa-plus-circle"></i> Add Listing</a>
						</li>

							{% else %}
							<a class="nav-link login-button" href= "{% url 'login_page' %}" >Login</a>
							{% endif %}
							
						</li>
						
					</ul>
				</div>
			</nav>
		</div>
	</div>
</div>
</section>


<div class="container">
	<body>
	{% block content %}
	{% endblock%}
	</body>
</div>
</html>





<!-- JAVASCRIPTS -->
<script src="{% static 'jQuery/jquery.min.js'  %}"></script>
<script src= "{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap-slider.js' %}"></script>
  <!-- tether js -->
<script src="{% static 'tether/js/tether.min.js' %}"></script>
<script src="{% static 'raty/jquery.raty-fa.js' %}"></script>
<script src="{% static 'slick-carousel/slick/slick.min.js' %}"></script>
<script src="{% static 'jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'fancybox/jquery.fancybox.pack.js' %}"></script>
<script src="{% static 'smoothscroll/SmoothScroll.min.js' %}"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
<script src="{% static 'google-map/gmap.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

working/templates/home_page.html
{% extends 'base.html'%}


{% block content %}

<div>
	<h1>Welcome to Marketplace</h1>

</div>

{% for product in products.all %}
<div class="row">
	<div class="col-2" onclick="window.location='{% url 'detail_page' product.id %}'" style="cursor: pointer;">
		<img src='{{ product.image.url }}' style="width:60px;height:60px;" class='img-fluid' />
	</div>
	<div class="col-6" onclick="window.location='{% url 'detail_page' product.id %}'" style="cursor: pointer;">
		<h2>{{ product.name}}</h2>
		<p>{{ product.summary}}</p>
		
	</div>
	<div class="col-4">
		<a href="javascript:{document.getElementById('upvote{{ product.id }}').submit()}"> <button class="btn btn-primary btn-lg btn-block"><span class="fas fa-thumbs-up"></span> Upvote {{ product.votes_total}}</button></a>
	</div>
</div>
<form id="upvote{{ product.id }}" method="POST" action="{% url 'prod_upvote' product.id %}">
	{% csrf_token %}
	<input type="hidden">

</form>

{% endfor %}

{% endblock %}