carts/urls.py
from django.conf.urls import url
from . views import carthome, cartupdate, checkout_home
from django.urls import path, include

app_name='carts'
urlpatterns =[
	path('', carthome, name='carthome'),
	path('checkout_home/', checkout_home, name='checkout'),
    path('cartupdate/', cartupdate, name='cartupdate'),
]

working/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from products.views import ProductListView, ProductDetailView,upvote, addListing
from carts.views import carthome



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home_page'),
    path('products/', ProductListView.as_view(), name='product_page'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='detail_page'),
    path('<int:product_id>/upvote', upvote, name='prod_upvote'),
    path('addListing', addListing, name='addListing_page'),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls', namespace= 'carts')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed

User 	=	settings.AUTH_USER_MODEL


class CartManager(models.Manager):
	
	def new_or_get(self, request):
			cart_id		= request.session.get("cart_id", None)
			qs	= self.get_queryset().filter(id=cart_id)
			if qs.count()	== 1:
				new_obj = False
				cart_obj = qs.first()
				if request.user.is_authenticated and cart_obj.user is None:
					cart_obj.user = request.user
					cart_obj.save()
			else:
				cart_obj = Cart.objects.new(user=request.user)
				new_obj	 = True
				request.session['cart_id'] = cart_obj.id
			return cart_obj, new_obj

	def new(self, user=None):
		user_obj = None
		if user is not None:
			if user.is_authenticated:
				user_obj = user
		return self.model.objects.create(user=user_obj)

class Cart(models.Model):
	user 		= models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	products	= models.ManyToManyField(Product, blank=True)	
	subtotal	= models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	total		= models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	updated		= models.DateTimeField(auto_now=True)
	timestamp	= models.DateTimeField(auto_now_add=True)

	objects		= CartManager()

	def __str__(self):
		return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action,  *args, **kwargs):
	if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
		products 	= instance.products.all()
		total 		= 0
		for x in products:
			total	+= x.price
		instance.subtotal = total
		instance.save() 
	
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
	if instance.subtotal > 0:
		instance.total = instance.subtotal + 3
	else:
		instance.total=0

pre_save.connect(pre_save_cart_receiver, sender = Cart)

carts/views.py
from django.shortcuts import render, redirect
from orders.models import Order
from products.models import Product
from .models import Cart

# Create your views here.


def carthome(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	context = {'cart':cart_obj}
	return render (request, 'carts/home.html', {'cart':cart_obj})

def cartupdate(request):
	product_id			= request.POST.get('product_id')
	if product_id is not None:
		try:
			product_obj 		= Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			print("Show message to user, product is gone?")
			return redirect('/cart/')
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if product_obj in cart_obj.products.all():
			cart_obj.products.remove(product_obj)

		else:
			cart_obj.products.add(product_obj) #cart_obj.products.add(id=product_id)
		request.session['cart_items'] = cart_obj.products.count()
		#for x in cart_obj.products.all():
			#print(x)
	#return redirect('/products/'+str(product_id))
		return redirect('/cart/') # or return redirect('carts:carthome')

def checkout_home(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.products.count() == 0:
		return redirect('/cart/')
	else:
		order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
	return render(request,'carts/checkout.html',{"order": order_obj})

carts/templates/carts/checkout.html
{% extends 'base.html'%}


{% block content %}
<h1>Checkout</h1>

<p> Cart Total: {{order.cart.total}}  </p>
<p> Shipping Total: {{order.shipping_total}} </p>
<p> Order Total: {{order.order_total}} </p>
{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html'%}


{% block content %}
<h1>Cart</h1>


{% if cart.products.exists %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
  
    </tr>
  </thead>
  <tbody>
  	{% for product in cart.products.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'detail_page' product.id %}">{{ product.name }}</a>



      	{% include 'products/updatecart.html' with product=product cart=cart in_cart=True %}
      </td>
      <td>{{ product.price }}</td>
      
    </tr>
    {% endfor %}
    <tr>
      <th colspan="2"></th>
      <td><b> Subtotal</b> {{ cart.subtotal }}</td>
    </tr>
    <tr>
      <th colspan="2"></th>
      <td><b> Total</b> {{ cart.total }}</td>
    </tr>
    <tr>
      <th colspan="2"></th>
      <td><a class="btn btn-success"   href='{% url "carts:checkout" %}'>Checkout </a></td>
    </tr>

  </tbody>
</table>
{% else %}
<p class="lead"> Cart is empty</p>
{% endif %}

{% endblock %}