carts/urls.py
from django.conf.urls import url
from . views import carthome, cartupdate, checkout_home
from django.urls import path, include

app_name='carts'
urlpatterns =[
	path('', carthome, name='carthome'),
	path('checkout_home/', checkout_home, name='checkout'),
    path('cartupdate/', cartupdate, name='cartupdate'),
]

working/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from products.views import ProductListView, ProductDetailView,upvote, addListing
from carts.views import carthome



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home_page'),
    path('products/', ProductListView.as_view(), name='product_page'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='detail_page'),
    path('<int:product_id>/upvote', upvote, name='prod_upvote'),
    path('addListing', addListing, name='addListing_page'),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls', namespace= 'carts')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# create category model
class Category(models.Model):
	name 		= models.CharField(max_length=250, unique=True)
	slug 		= models.SlugField(max_length=250, unique=True)
	description = models.TextField(blank=True)
	icon		= models.ImageField(upload_to = 'category/', blank=True)

	class Meta:
		ordering 			= ('name',)
		verbose_name 		= 'category'
		verbose_name_plural = 'categories'
	def __str__(self):
		return '{}'.format(self.name)

	def _get_unique_slug(self):
		slug = slugify(self.name)
		unique_slug = slug
		num = 1
		while Category.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save(*args, **kwargs)






class ProductManager(models.Manager):
	def get_by_id(self,id):
		qs 	=	self.get_queryset().filter(id=id)
		if qs.count()==1:
			return qs.first()
		return None


class Product(models.Model):
	name 		= models.CharField(max_length=250, unique=False) #review unique attribute	
	description = models.TextField(blank=True)
	price 		= models.DecimalField(max_digits=10, decimal_places=2)
	image 		= models.ImageField(upload_to= 'product/',blank=True)
	stock 		= models.IntegerField()
	available 	= models.BooleanField(default=True)
	created 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)
	votes_total = models.IntegerField(default=1)
	creator 	= models.ForeignKey(User, on_delete=models.CASCADE)
	slug 		= models.SlugField(max_length=250, unique=False) #review unique attribute
	category 	= models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

	def get_abosolute_url(self):
		return "{pk}".format(pk=self.pk)

	def summary(self):
		return self.description[:100]

	class Meta:
		ordering =('votes_total',)
		verbose_name = 'product'
		verbose_name_plural = 'products'
	def __str__(self):
		return '{}'.format(self.name)

	def _get_unique_slug(self):
		slug = slugify(self.name)
		unique_slug = slug
		num = 1
		while Product.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save(*args, **kwargs)

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from carts.models import Cart
from .models import Product, Category
from django.utils import timezone
from django import forms


class ProductListView(ListView):
	queryset	=	Product.objects.all().order_by('-votes_total')


	#def product_List_View(request): (Does the same thing as above)
			#	queryset	= Product.objects.all()
			#	context		=	{
			#			'objects_list':queryset
			#	}
			#	return render(request,"product/product_List_View.html",context)

	#def get_context_data(self, *args, **kwargs):
	#	context = super(ProductListView, self).get_context_data(*args, **kwargs)
	#	return context 
	def get_object(self, *args, **kwargs):
		request 	= self.request
		pk			= self.kwargs.get('pk')
		instance	= Product.object.get_by_id(pk)
		if instance is None:
			raise Http404('Product Does Not Exist')
		return instance

class ProductDetailView(DetailView):
	queryset	=	Product.objects.all()
	template_name	=	'products/detail.html'

	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		cart_obj = Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context
			
################# Merger Starting Here ##############

@login_required(login_url="/accounts/login")
def upvote(request, product_id):
	if request.method == 'POST':
		product = get_object_or_404(Product, pk=product_id)
		product.votes_total +=1
		product.save()
		return redirect('/products/'+str(product.id))
	else:
		return redirect('/products/'+str(product.id))


@login_required(login_url="/accounts/login")
def addListing(request): #Change this to home page in product later
	if request.method == 'POST':
		if request.POST['product_name'] and request.POST['product_description'] and request.POST['product_price'] and request.FILES['product_image'] and request.POST['product_stock']:
			category = Category.objects.all() 
			product = Product()
			product.name 		= request.POST['product_name']
			product.description = request.POST['product_description']
			product.price 		=request.POST['product_price']	
			product.image 		= request.FILES['product_image']
			product.stock 		=request.POST['product_stock']	
			#product.available	=
			product.created 	=timezone.datetime.now()
			product.updated 	=timezone.datetime.now()
			product.votes_tot	= 1
			product.creator 	= request.user
			for x in category:
				if request.POST['product_category']==x.name:
					product.category=x
			product.save()
			return redirect('/products/'+str(product.id))
		else:
			return render(request, 'products/addListing.html', {'error':'Missing Required Fields'})
	else:
		return render(request, 'products/addListing.html') # Change this to home page in product later

products/templates/products/addListing.html
{% extends 'base.html'%}

{% block content %}

<section class="login py-5 border-top-1">
	<div class="container">
		{% if error %}
		{{ error }}
		{% endif %}
		<div class="row justify-content-center">
			<div class="col-lg-5 col-md-8 align-item-center">
				<div class="border">
					<h3 class="bg-gray p-4">Add a Listing</h3>
					<form method="POST" action="{% url 'addListing_page' %}" enctype="multipart/form-data">
						{% csrf_token %}
						<fieldset class="p-4">
							Name:
							<input type = "text" class="border p-3 w-100 my-2" name="product_name">
							Description:
							<input type = "text" class="border p-3 w-100 my-2" name="product_description">
							Category:
							<select type = "text" class="border p-3 w-100 my-2" name="product_category">
  								<option value="Vehicles">Vehicles</option>
  								<option value="Electronic">Electronic</option>
  								<option value="Travel">Travel</option>
  								<option value="Restaurant">Restaurant</option>
							</select>
							Price:
							<input type = "text" class="border p-3 w-100 my-2" name="product_price">
							Image:
							<input type = "file" class="border p-3 w-100 my-2" name="product_image">
							Stock:
							<input type = "text" class="border p-3 w-100 my-2" name="product_stock">

																				
							<button type="submit" class="d-block py-3 px-5 bg-primary text-white border-0 rounded font-weight-bold mt-3">Add Product</button>
							
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

products/templates/products/detail.html
{% extends 'base.html'%}


{% block content %}

This is the product detail<br>

<div class="row">
	<div class="col-12 col-md-6">
		<h1>{{object.name}}</h1>
		{{object.timestamp|timesince }}
		{{object.description}}<br>
		{% if object.image %}
		<img src="{{ object.image.url}}" class="img-fluid">
		{% endif %}
	</div>	

	<div class="col-12 col-md-6">
		<!-- {% include 'products/updatecart.html' with product=object cart=cart %} -->

		<form method="POST" action='{% url "carts:cartupdate" %}' class="form">
				{% csrf_token %}
				<input type="hidden" name="product_id" value="{{ product.id }}">
				{% if in_cart %}
					<button type="submit" class="btn btn-link btn-sm" style="padding: 0px"><small>remove?</small></button>
				{% else %}
					{% if object in cart.products.all %}
						In cart <button type="submit" class="btn btn-link">Remove?</button>
					{% else %}
						<button type="submit" class="btn btn-success"> Add to cart</button>
					{% endif %}
				{% endif %}
			{% for object in cart.products.all%}
			{{ product.name }}
			{% endfor %}
	</form>





	</div>
</div>	



{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html'%}


{% block content %}

This is the product list<br>

{% for obj in object_list %}

<a href="{{ obj.get_abosolute_url }}">{{obj.name}} </a> <br>

{% endfor %}


{% endblock %}

products/templates/products/updatecart.html
<form method="POST" action='{% url "carts:cartupdate" %}' class="form">
	{% csrf_token %}
	<input type="hidden" name="product_id" value="{{ product.id }}">
	{% if in_cart %}
		<button type="submit" class="btn btn-link btn-sm" style="padding: 0px"><small>remove?</small></button>
	{% else %}
		{% if product in cart.products.all %}
			In cart <button type="submit" class="btn btn-link">Remove?</button>
		{% else %}
			<button type="submit" class="btn btn-success"> Add to cart</button>
		{% endif %}
	{% endif %}
<!-- {% for product in cart.products.all%}
{{ product.name }}
{% endfor %} -->
</form>